//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Models = new HashSet<Model>();
        }
    
        public int Level { get; set; }
        public double PerDay { get; set; }
        public string Name { get; set; }
        public Nullable<double> DayFine { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
    }
}
