//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int ID { get; set; }
        public int Year { get; set; }
        public int Manufacturer { get; set; }
        public int Level { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Group Group { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
    }
}
