//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int User { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int CarNumber { get; set; }
        public bool IsActive { get; set; }
        public int Branch { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Car Car { get; set; }
        public virtual User User1 { get; set; }
    }
}
